#My First Workflow
 
name: workflow1
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "Hello from SP"
          sleep 30
      - name: step2 for testing
        run: |
          cat /etc/os-release 
          hostname
          touch /tmp/sp
          sleep 30
    ## Name us not important in a step
      - run: uname -a
